services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-system-container
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

  database:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./migrations:/flyway/sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysql", "-u${DB_USER}", "-h${DB_HOST}", "-p${DB_PASSWORD}", "-e", "USE ${DB_NAME};"]
      interval: 25s
      timeout: 5s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway-container
    environment:
      FLYWAY_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
      FLYWAY_USER: ${DB_USER}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - database
    command: -connectRetries=60 migrate

    

volumes:
  mysql_volume:
  es_data: